# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hackathon_gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1134, 907)
        self.main_frame = QtWidgets.QFrame(Dialog)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 321, 891))
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.img_rad_btn = QtWidgets.QRadioButton(self.main_frame)
        self.img_rad_btn.setGeometry(QtCore.QRect(0, 0, 71, 22))
        self.img_rad_btn.setObjectName("img_rad_btn")
        self.radioButton = QtWidgets.QRadioButton(self.main_frame)
        self.radioButton.setGeometry(QtCore.QRect(90, 0, 81, 22))
        self.radioButton.setObjectName("radioButton")
        self.label_2 = QtWidgets.QLabel(self.main_frame)
        self.label_2.setGeometry(QtCore.QRect(60, 720, 67, 17))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.detection_frame = QtWidgets.QFrame(self.main_frame)
        self.detection_frame.setGeometry(QtCore.QRect(0, 40, 321, 301))
        self.detection_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detection_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detection_frame.setObjectName("detection_frame")
        self.det_lbl = QtWidgets.QLabel(self.detection_frame)
        self.det_lbl.setGeometry(QtCore.QRect(10, 0, 91, 17))
        self.det_lbl.setObjectName("det_lbl")
        self.det_slct_img_frame = QtWidgets.QFrame(self.detection_frame)
        self.det_slct_img_frame.setGeometry(QtCore.QRect(0, 20, 321, 131))
        self.det_slct_img_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.det_slct_img_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.det_slct_img_frame.setObjectName("det_slct_img_frame")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.det_slct_img_frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 311, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.det_img_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.det_img_grid.setObjectName("det_img_grid")
        self.det_img_run_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.det_img_run_btn.setObjectName("det_img_run_btn")
        self.det_img_grid.addWidget(self.det_img_run_btn, 2, 1, 1, 1)
        self.det_img_brw_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.det_img_brw_btn.setObjectName("det_img_brw_btn")
        self.det_img_grid.addWidget(self.det_img_brw_btn, 0, 1, 1, 1)
        self.det_img_txtbx = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.det_img_txtbx.setObjectName("det_img_txtbx")
        self.det_img_grid.addWidget(self.det_img_txtbx, 0, 0, 1, 1)
        self.det_img_lbl = QtWidgets.QLabel(self.det_slct_img_frame)
        self.det_img_lbl.setGeometry(QtCore.QRect(130, 0, 51, 17))
        self.det_img_lbl.setObjectName("det_img_lbl")
        self.dete_vid_frame = QtWidgets.QFrame(self.detection_frame)
        self.dete_vid_frame.setGeometry(QtCore.QRect(0, 150, 321, 151))
        self.dete_vid_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dete_vid_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dete_vid_frame.setObjectName("dete_vid_frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.dete_vid_frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 311, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.det_vid_grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.det_vid_grid.setObjectName("det_vid_grid")
        self.det_vid_txtbx = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.det_vid_txtbx.setObjectName("det_vid_txtbx")
        self.det_vid_grid.addWidget(self.det_vid_txtbx, 0, 0, 1, 1)
        self.det_vid_captr_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.det_vid_captr_btn.setObjectName("det_vid_captr_btn")
        self.det_vid_grid.addWidget(self.det_vid_captr_btn, 2, 1, 1, 1)
        self.det_vid_brsrun_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.det_vid_brsrun_btn.setObjectName("det_vid_brsrun_btn")
        self.det_vid_grid.addWidget(self.det_vid_brsrun_btn, 0, 1, 1, 1)
        self.det_vid_stop_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.det_vid_stop_btn.setObjectName("det_vid_stop_btn")
        self.det_vid_grid.addWidget(self.det_vid_stop_btn, 3, 1, 1, 1)
        self.det_vid_lvcam_lbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.det_vid_lvcam_lbl.setObjectName("det_vid_lvcam_lbl")
        self.det_vid_grid.addWidget(self.det_vid_lvcam_lbl, 2, 0, 1, 1)
        self.det_vid_lbl = QtWidgets.QLabel(self.dete_vid_frame)
        self.det_vid_lbl.setGeometry(QtCore.QRect(130, 0, 51, 17))
        self.det_vid_lbl.setObjectName("det_vid_lbl")
        self.search_frame = QtWidgets.QFrame(self.main_frame)
        self.search_frame.setGeometry(QtCore.QRect(0, 340, 321, 551))
        self.search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_frame.setObjectName("search_frame")
        self.srch_Lbl = QtWidgets.QLabel(self.search_frame)
        self.srch_Lbl.setGeometry(QtCore.QRect(10, 0, 67, 17))
        self.srch_Lbl.setObjectName("srch_Lbl")
        self.search_img_frame = QtWidgets.QFrame(self.search_frame)
        self.search_img_frame.setGeometry(QtCore.QRect(0, 20, 321, 91))
        self.search_img_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_img_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_img_frame.setObjectName("search_img_frame")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.search_img_frame)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 30, 311, 51))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.srch_img_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.srch_img_grid.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.srch_img_grid.setObjectName("srch_img_grid")
        self.srch_img_brws_btn = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.srch_img_brws_btn.setObjectName("srch_img_brws_btn")
        self.srch_img_grid.addWidget(self.srch_img_brws_btn, 1, 1, 1, 1)
        self.srch_img_txtbx = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.srch_img_txtbx.setObjectName("srch_img_txtbx")
        self.srch_img_grid.addWidget(self.srch_img_txtbx, 1, 0, 1, 1)
        self.srch_img_lbl = QtWidgets.QLabel(self.search_img_frame)
        self.srch_img_lbl.setGeometry(QtCore.QRect(130, 0, 51, 17))
        self.srch_img_lbl.setObjectName("srch_img_lbl")
        self.srch_obj_frame = QtWidgets.QFrame(self.search_frame)
        self.srch_obj_frame.setGeometry(QtCore.QRect(0, 110, 321, 71))
        self.srch_obj_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.srch_obj_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.srch_obj_frame.setObjectName("srch_obj_frame")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.srch_obj_frame)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 10, 311, 51))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.srch_obj_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.srch_obj_grid.setObjectName("srch_obj_grid")
        self.srch_obj_brws_btn = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.srch_obj_brws_btn.setObjectName("srch_obj_brws_btn")
        self.srch_obj_grid.addWidget(self.srch_obj_brws_btn, 0, 1, 1, 1)
        self.srch_obj_txtbx = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.srch_obj_txtbx.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.srch_obj_txtbx.setText("")
        self.srch_obj_txtbx.setObjectName("srch_obj_txtbx")
        self.srch_obj_grid.addWidget(self.srch_obj_txtbx, 0, 0, 1, 1)
        self.gridLayoutWidget_6.raise_()
        self.srch_rslt_frame = QtWidgets.QFrame(self.search_frame)
        self.srch_rslt_frame.setGeometry(QtCore.QRect(0, 180, 321, 81))
        self.srch_rslt_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.srch_rslt_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.srch_rslt_frame.setObjectName("srch_rslt_frame")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.srch_rslt_frame)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(0, 20, 311, 52))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.srch_rslt_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.srch_rslt_grid.setObjectName("srch_rslt_grid")
        self.srch_img_shw_btn = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.srch_img_shw_btn.setObjectName("srch_img_shw_btn")
        self.srch_rslt_grid.addWidget(self.srch_img_shw_btn, 0, 1, 1, 1)
        self.srch_img_cmbx = QtWidgets.QComboBox(self.gridLayoutWidget_7)
        self.srch_img_cmbx.setObjectName("srch_img_cmbx")
        self.srch_rslt_grid.addWidget(self.srch_img_cmbx, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.srch_rslt_frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 17))
        self.label.setObjectName("label")
        self.srch_vid_frame = QtWidgets.QFrame(self.search_frame)
        self.srch_vid_frame.setGeometry(QtCore.QRect(0, 260, 321, 81))
        self.srch_vid_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.srch_vid_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.srch_vid_frame.setObjectName("srch_vid_frame")
        self.srch_vid_Lbl = QtWidgets.QLabel(self.srch_vid_frame)
        self.srch_vid_Lbl.setGeometry(QtCore.QRect(130, 0, 67, 17))
        self.srch_vid_Lbl.setObjectName("srch_vid_Lbl")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.srch_vid_frame)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.srch_slct_vid_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.srch_slct_vid_grid.setObjectName("srch_slct_vid_grid")
        self.srch_slct_video_brw_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.srch_slct_video_brw_btn.setObjectName("srch_slct_video_brw_btn")
        self.srch_slct_vid_grid.addWidget(self.srch_slct_video_brw_btn, 1, 1, 1, 1)
        self.srch_slct_vid_txtbx = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.srch_slct_vid_txtbx.setObjectName("srch_slct_vid_txtbx")
        self.srch_slct_vid_grid.addWidget(self.srch_slct_vid_txtbx, 1, 0, 1, 1)
        self.srch_vid_Lbl.raise_()
        self.gridLayoutWidget_3.raise_()
        self.srch_vid_obj_frame = QtWidgets.QFrame(self.search_frame)
        self.srch_vid_obj_frame.setGeometry(QtCore.QRect(0, 340, 321, 71))
        self.srch_vid_obj_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.srch_vid_obj_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.srch_vid_obj_frame.setObjectName("srch_vid_obj_frame")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.srch_vid_obj_frame)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 311, 51))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.srch_vid_obj_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.srch_vid_obj_grid.setObjectName("srch_vid_obj_grid")
        self.srch_vid_obj_srch_btn = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.srch_vid_obj_srch_btn.setObjectName("srch_vid_obj_srch_btn")
        self.srch_vid_obj_grid.addWidget(self.srch_vid_obj_srch_btn, 0, 1, 1, 1)
        self.srch_vid_obj_txtbx = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.srch_vid_obj_txtbx.setObjectName("srch_vid_obj_txtbx")
        self.srch_vid_obj_grid.addWidget(self.srch_vid_obj_txtbx, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.search_frame)
        self.frame.setGeometry(QtCore.QRect(0, 410, 321, 151))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(0, 20, 311, 101))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.srch_vid_rslt_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.srch_vid_rslt_grid.setObjectName("srch_vid_rslt_grid")
        self.srch_vid_rslt_play_btn = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        self.srch_vid_rslt_play_btn.setObjectName("srch_vid_rslt_play_btn")
        self.srch_vid_rslt_grid.addWidget(self.srch_vid_rslt_play_btn, 1, 1, 1, 1)
        self.srch_vid_rslt_Ld_btn = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        self.srch_vid_rslt_Ld_btn.setObjectName("srch_vid_rslt_Ld_btn")
        self.srch_vid_rslt_grid.addWidget(self.srch_vid_rslt_Ld_btn, 0, 1, 1, 1)
        self.srch_vid_rslt_cmbx = QtWidgets.QComboBox(self.gridLayoutWidget_8)
        self.srch_vid_rslt_cmbx.setObjectName("srch_vid_rslt_cmbx")
        self.srch_vid_rslt_grid.addWidget(self.srch_vid_rslt_cmbx, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.label_3.setObjectName("label_3")
        self.srch_Lbl.raise_()
        self.search_img_frame.raise_()
        self.srch_obj_frame.raise_()
        self.srch_rslt_frame.raise_()
        self.srch_vid_frame.raise_()
        self.srch_vid_obj_frame.raise_()
        self.frame.raise_()
        self.video_frame = QtWidgets.QFrame(Dialog)
        self.video_frame.setGeometry(QtCore.QRect(330, 0, 771, 891))
        self.video_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.video_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.video_frame.setObjectName("video_frame")
        self.graphicsView = QtWidgets.QGraphicsView(self.video_frame)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 831, 901))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.gridLayoutWidget_8.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.img_rad_btn.setText(_translate("Dialog", "Image"))
        self.radioButton.setText(_translate("Dialog", "Video"))
        self.det_lbl.setText(_translate("Dialog", "DETECTION"))
        self.det_img_run_btn.setText(_translate("Dialog", "Run"))
        self.det_img_brw_btn.setText(_translate("Dialog", "Browse"))
        self.det_img_txtbx.setPlaceholderText(_translate("Dialog", "Select imagefolder"))
        self.det_img_lbl.setText(_translate("Dialog", "Image"))
        self.det_vid_txtbx.setPlaceholderText(_translate("Dialog", "Select video"))
        self.det_vid_captr_btn.setText(_translate("Dialog", "Capture"))
        self.det_vid_brsrun_btn.setText(_translate("Dialog", "Browse Run"))
        self.det_vid_stop_btn.setText(_translate("Dialog", "Stop Capturing"))
        self.det_vid_lvcam_lbl.setText(_translate("Dialog", "Live Camera"))
        self.det_vid_lbl.setText(_translate("Dialog", "Video"))
        self.srch_Lbl.setText(_translate("Dialog", "SEARCH"))
        self.srch_img_brws_btn.setText(_translate("Dialog", "Browse"))
        self.srch_img_txtbx.setPlaceholderText(_translate("Dialog", "Select imagefolder"))
        self.srch_img_lbl.setText(_translate("Dialog", "Image"))
        self.srch_obj_brws_btn.setText(_translate("Dialog", "Search"))
        self.srch_obj_txtbx.setPlaceholderText(_translate("Dialog", "Enter objectname"))
        self.srch_img_shw_btn.setText(_translate("Dialog", "Show"))
        self.label.setText(_translate("Dialog", "Searchresult"))
        self.srch_vid_Lbl.setText(_translate("Dialog", "Video"))
        self.srch_slct_video_brw_btn.setText(_translate("Dialog", "Browse"))
        self.srch_slct_vid_txtbx.setPlaceholderText(_translate("Dialog", "Select video"))
        self.srch_vid_obj_srch_btn.setText(_translate("Dialog", "Search"))
        self.srch_vid_obj_txtbx.setPlaceholderText(_translate("Dialog", "Search result"))
        self.srch_vid_rslt_play_btn.setText(_translate("Dialog", "Play"))
        self.srch_vid_rslt_Ld_btn.setText(_translate("Dialog", "Load"))
        self.label_3.setText(_translate("Dialog", "Search result"))

